//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string ProductArticleNumber { get; set; }
        public int IdProductName { get; set; }
        public int IdUnion { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<byte> ProductDiscountMax { get; set; }
        public int IdProizvoditel { get; set; }
        public int IdPostavshic { get; set; }
        public int IdCategoryProduct { get; set; }
        public Nullable<byte> ProductDiscount { get; set; }
        public string Count { get; set; }
        public string Description { get; set; }
        public string ImageName { get; set; }
        public byte[] ImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual Postavshic Postavshic { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductName ProductName { get; set; }
        public virtual Proizvoditel Proizvoditel { get; set; }
        public virtual Union Union { get; set; }
    }
}
